kind: Namespace
apiVersion: v1
metadata:
  name: rotelic
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alloy-cfg
  namespace: rotelic
data:
  alloy-cfg.river: |
    logging {
      level  = "debug"
    }
    
    otelcol.receiver.nria "default" {
      endpoint = ":4444"
          
      output {
        metrics = [otelcol.processor.batch.default.input]
      }
    }
    
    otelcol.processor.batch "default" {
      output {
        metrics = [otelcol.exporter.otlphttp.default.input]
        logs    = [otelcol.exporter.otlphttp.default.input]
        traces  = [otelcol.exporter.otlphttp.default.input]
      }
    }
    
    otelcol.exporter.otlphttp "default" {
      client {
        endpoint = "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"
        auth     = otelcol.auth.basic.grafana_cloud.handler
      }
    }
    
    otelcol.auth.basic "grafana_cloud" {
      username = sys.env("GRAFANA_CLOUD_USER")
      password = sys.env("GRAFANA_CLOUD_API_KEY")
    }